version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket cake-form-files --output-template-file outputCFTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputCFTemplate.yaml