version: 0.2
env:
  variables:
    INPUT_FILE: "template.yml"
    S3_BUCKET: "cake-form-files"
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template-file outputCFTemplate.yaml
artifacts:
  files:
    - outputCFTemplate.yaml