AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Lambda Deployment Template
Resources:
  AddCakeLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: addCakeDetails.lambda_handler
      Runtime: python3.9
      CodeUri: functions/
      Description: 'Lambda function to add a new Cake'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::109598254717:role/s3_json_dynamodb_role'
      Events:
        getCakeAPI:
          Type: Api
          Properties:
            Path: /cakedetailsresource
            Method: post
      Environment:
        Variables:
          REGION: us-east-2
  GetCakeLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getCakeDetails.lambda_handler
      Runtime: python3.9
      CodeUri: functions/
      Description: 'Lambda function to get cake details'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::109598254717:role/s3_json_dynamodb_role'
      Events:
        getCakeAPI:
          Type: Api
          Properties:
            Path: /cakedetailsresource
            Method: get
      Environment:
        Variables:
          REGION: us-east-2
  GetCakeLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: deleteCakeDetails.lambda_handler
      Runtime: python3.9
      CodeUri: functions/
      Description: 'Lambda function to get cake details'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::109598254717:role/s3_json_dynamodb_role'
      Events:
        getCakeAPI:
          Type: Api
          Properties:
            Path: /cakedetailsresource
            Method: delete
      Environment:
        Variables:
          REGION: us-east-2